// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-restaurant-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_restaurant_info_default = defineTool({
  name: "get_restaurant_info",
  title: "Get restaurant info",
  description: "Returns Cascade Premier's contact details, hours, location, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Cascade Premier",
      tagline: "Authentic Kenyan Dining in Thika Town",
      location: "Thika Town, Kiambu County, Kenya",
      google_maps: "https://maps.app.goo.gl/GypH5QrnLeuq3xGb6",
      phone: "+254 708 888 444",
      whatsapp: "https://wa.me/254708888444",
      tiktok: "https://www.tiktok.com/@cascade_kitchens0",
      hours: {
        "Monday\u2013Saturday": "6:00 AM \u2013 9:00 PM",
        "Sunday": "7:00 AM \u2013 9:00 PM"
      },
      price_range: "KES 500 \u2013 1,000 per person",
      rating: "4.1 (1,064+ Google reviews)",
      website: "https://cascade-digital-elegance.lovable.app",
      known_for: [
        "Legendary Uji Special (calabash-served arrowroot, honey & cassava porridge)",
        "Artisan pizza",
        "Authentic Kenyan cuisine",
        "Event venues seating 200+"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-menu.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var MENU = {
  breakfast: {
    label: "Breakfast",
    items: [
      { name: "Uji Special", description: "Arrowroot, honey & cassava porridge served in a calabash", price_kes: 250 },
      { name: "Mandazi & Tea", description: "Freshly fried mandazi with masala chai", price_kes: 150 },
      { name: "Full Breakfast Platter", description: "Eggs, sausage, toast, beans & fresh juice", price_kes: 450 },
      { name: "Bacon & Gizzards", description: "Crispy bacon with seasoned gizzards", price_kes: 400 }
    ]
  },
  chicken: {
    label: "Chicken",
    items: [
      { name: "Chicken Curry", price_kes: 490 },
      { name: "Supreme Chicken", price_kes: 590 },
      { name: "Chicken In Coconut Sauce", price_kes: 545 },
      { name: "Shawarma", description: "With Chips/Rice/Ugali/Chapati/Pilau/Mukimo", price_kes: 500 },
      { name: "Deep Fried Chicken \xBC", price_kes: 460 }
    ]
  },
  fish: {
    label: "Fish",
    items: [
      { name: "Deep Fried Whole Tilapia", price_kes: 600 },
      { name: "Wet Fried Whole Tilapia", price_kes: 600 },
      { name: "Fish Curry", price_kes: 600 },
      { name: "Fish Fillet", price_kes: 410 },
      { name: "Lemon Baked Fish", price_kes: 555 }
    ]
  },
  fast_food: {
    label: "Fast Food",
    items: [
      { name: "Artisan Pizza (Medium)", price_kes: 800 },
      { name: "Artisan Pizza (Large)", price_kes: 1200 },
      { name: "Masala Fries", price_kes: 250 },
      { name: "Chicken Sandwich", price_kes: 405 },
      { name: "Samosa (3 pcs)", price_kes: 150 }
    ]
  },
  wraps: {
    label: "Wraps",
    items: [
      { name: "Chicken Wrap", price_kes: 290 },
      { name: "Beef Wrap", price_kes: 290 },
      { name: "Bacon Wrap", price_kes: 330 },
      { name: "Vegetable Wrap", price_kes: 290 }
    ]
  },
  soups: {
    label: "Soups",
    items: [
      { name: "Oxtail Soup", price_kes: 245 },
      { name: "Cream Of Chicken Soup", price_kes: 245 },
      { name: "Bone Soup", price_kes: 210 }
    ]
  },
  coffee: {
    label: "Coffee",
    items: [
      { name: "Cappuccino", price_kes: 265 },
      { name: "Americano", price_kes: 265 },
      { name: "Latte", price_kes: 265 },
      { name: "Mocha", price_kes: 265 }
    ]
  },
  drinks: {
    label: "Drinks",
    items: [
      { name: "Assorted Milk Shakes", price_kes: 310 },
      { name: "Fresh Passion Juice", price_kes: 185 },
      { name: "Delmonte Juice 1L", price_kes: 400 },
      { name: "Soda 500ml", price_kes: 100 }
    ]
  }
};
var get_menu_default = defineTool2({
  name: "get_menu",
  title: "Get menu",
  description: "Returns Cascade Premier's menu, optionally filtered to a single category.",
  inputSchema: {
    category: z.enum(["breakfast", "chicken", "fish", "fast_food", "wraps", "soups", "coffee", "drinks"]).optional().describe("Menu category to fetch. Omit to return the full menu.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const data = category ? { [category]: MENU[category] } : MENU;
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-reservations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_reservations_default = defineTool3({
  name: "list_reservations",
  title: "List reservations",
  description: "List Cascade Premier reservations, optionally filtered by status or date. Returns up to 50 records ordered by date (newest first).",
  inputSchema: {
    status: z2.enum(["pending", "confirmed", "completed", "cancelled"]).optional().describe("Filter by reservation status."),
    date: z2.string().optional().describe("Filter by exact reservation date (YYYY-MM-DD)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum records to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, date, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY);
    let query = supabase.from("reservations").select("*").order("reservation_date", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (date) query = query.eq("reservation_date", date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, reservations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-reservation.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_reservation_default = defineTool4({
  name: "create_reservation",
  title: "Create a reservation",
  description: "Book a table at Cascade Premier for a specific date, time, and party size.",
  inputSchema: {
    full_name: z3.string().trim().min(1).max(100).describe("Guest's full name."),
    phone: z3.string().trim().min(6).max(15).describe("Contact phone number in international format (e.g. +254712345678)."),
    reservation_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Reservation date in YYYY-MM-DD format."),
    reservation_time: z3.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).describe("Reservation time in 24h HH:MM format."),
    guests: z3.string().min(1).describe("Number of guests (e.g. '2', '4', '10+')."),
    occasion: z3.enum(["casual", "birthday", "business", "bridal", "conference", "other"]).optional().describe("Occasion type."),
    special_requests: z3.string().max(500).optional().describe("Any special requirements.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY);
    const { data, error } = await supabase.from("reservations").insert({
      full_name: input.full_name,
      phone: input.phone,
      reservation_date: input.reservation_date,
      reservation_time: input.reservation_time,
      guests: input.guests,
      occasion: input.occasion ?? null,
      special_requests: input.special_requests ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: `Failed to create reservation: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: `Reservation created for ${input.full_name} on ${input.reservation_date} at ${input.reservation_time} (${input.guests} guests). Status: pending confirmation.` }],
      structuredContent: { reservation: data }
    };
  }
});

// src/lib/mcp/tools/list-tables.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_tables_default = defineTool5({
  name: "list_tables",
  title: "List restaurant tables",
  description: "List all tables in the restaurant with their capacity, location, and current status (available, reserved, occupied).",
  inputSchema: {
    status: z4.enum(["available", "reserved", "occupied"]).optional().describe("Filter tables by current status."),
    min_capacity: z4.number().int().min(1).optional().describe("Only return tables with at least this many seats.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, min_capacity }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY);
    let query = supabase.from("restaurant_tables").select("*").order("table_number");
    if (status) query = query.eq("status", status);
    if (min_capacity) query = query.gte("capacity", min_capacity);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, tables: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_reviews_default = defineTool6({
  name: "list_reviews",
  title: "List customer reviews",
  description: "List approved customer reviews for Cascade Premier with star ratings.",
  inputSchema: {
    min_rating: z5.number().int().min(1).max(5).optional().describe("Only return reviews with at least this star rating."),
    limit: z5.number().int().min(1).max(50).optional().describe("Maximum reviews to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ min_rating, limit }) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY);
    let query = supabase.from("customer_reviews").select("id, name, rating, review_text, source, created_at").eq("is_approved", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (min_rating) query = query.gte("rating", min_rating);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cascade-premier-mcp",
  title: "Cascade Premier",
  version: "0.1.0",
  instructions: "Tools for Cascade Premier \u2014 an authentic Kenyan restaurant in Thika Town. Use `get_restaurant_info` for contact details, hours, and location. Use `get_menu` to browse dishes and prices (KES). Use `create_reservation` to book a table (all bookings start as pending until staff confirm). Use `list_reservations`, `list_tables`, and `list_reviews` to inspect current bookings, table availability, and customer feedback.",
  tools: [
    get_restaurant_info_default,
    get_menu_default,
    create_reservation_default,
    list_reservations_default,
    list_tables_default,
    list_reviews_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
